### ISSUE TITLE
System Environment Variables Unused 

### ISSUE THREAD

**Issue by niedzielski** [JCAndKSolutions/android-unit-test#100]
Setting environment variables have no effect. I have a test, `FooTest`, in a module, `foo-module` which I execute like so:

    gradle --debug -Dtest.single=FooTest -Drobolectric.logging=stdout :foo-module:test

  `robolectric.logging=stdout` is not passed to the tests. Setting the property in a test runner works fine:

    public class TestRunner extends RobolectricTestRunner {
        static {
            System.setProperty("robolectric.logging", "stdout");
        }

        public TestRunner(Class<?> testClass) throws InitializationError {
            super(testClass);
        }
    }

I've a silly workaround for reading in a .properties file in the TestRunner and manually setting all variables. The plugin is awesome but there are a lot of gotchas. If I open a pull request of known issues and workarounds, would you accept it?

**Comment by SuperJugy** [comment]
passing system variables will not work because the tests are run in their independent JVM which will not have this properties. but if you read the README, you will find a way to configure variables in the `build.gradle` thanks to the extension provided by this plugin.

**Comment by SuperJugy** [comment]
Here the important part:
```
androidUnitTest {
  testTasks { //Configures the test tasks.
    all { //Configures all the test tasks with the same values.
      systemProperties = ['test.prop2': 'value2', 'test.prop3': 'value3'] //Sets the system properties for the test JVM.
      systemProperties(['test.prop2': 'value2', 'test.prop3': 'value3']) //Adds several system properties for the test JVM.
      systemProperty 'test.prop1', 'value1' //Adds one system property for the test JVM.
    }
  }
}
```
