### ISSUE TITLE
Plugin does not handle sdk from `sdk-manager-plugin`

### ISSUE THREAD

**Issue by kkocel** [JCAndKSolutions/android-unit-test#103]
Even though I'm using `sdk-manager-plugin` it's impossible run the build.

> 02-Feb-2015 11:34:37	> Failed to apply plugin [id 'android-unit-test']
> 02-Feb-2015 11:34:37	   > failed to find Build Tools revision 21.1.2

**Comment by SuperJugy** [comment]
That is actually a problem with that plug-in not this. There was an error like this before reported already
