### ISSUE TITLE
Don't reference android plugin components until project.afterEvalute

### ISSUE THREAD

**Issue by Alexander--** [JCAndKSolutions/android-unit-test#107]
Currently this prevents android-sdk-manager from working with this plugin

**Comment by SuperJugy** [comment]
I'm going to deprecate this plugin since the new android plugin 1.1 already supports unit tests in JVM. So I don't think I'm going to fix this.

**Comment by Alexander--** [comment]
Are you sure? It does not look like Android plugin test support is mature yet. It still does not have per-variant tests and the API is limited and unstable.

**Comment by SuperJugy** [comment]
I believe the current state of the plug-in should be enough to give the android plug-in time to mature.

**Comment by Alexander--** [comment]
> give the android plug-in time to mature.

Which would be pretty ambitious, if you consider, that they are currently in terrible struggle to create their own javac/dex/Proguard replacement.

**Comment by nenick** [comment]
> It still does not have per-variant tests and the API is limited and unstable.

Hey Alexander I build an example project (with some variants) to check the new unit test support. I faced few issues, but for all of them I found a workaround. I haven't see any issues with build variants I would be glad if you describe your issue at my example project and we will try to get it work.

example project https://github.com/nenick/AndroidStudioAndRobolectric

**Comment by SuperJugy** [comment]
Yes, it was my understanding that the android plugin should give pretty much the same capabilities as this plugin except maybe for the JVM configuration like `forkEvery` and `maxHeap`, but that can be worked around or we can ask the android team to add it. they wouldn't have released 1.1 if it was unstable as you say. They had 1 or 2 release candidates before releasing.
