### ISSUE TITLE
AAR test dependencies

### ISSUE THREAD

**Issue by emilesvt** [JCAndKSolutions/android-unit-test#82]
Attempting to use assertj-android and I get the following:

```
error: package org.assertj.android.api does not exist
```

I've tried using both with/without the qualifier @aar, but no success.

```
testCompile 'com.squareup.assertj:assertj-android:1.0.0@aar'
```

or

```
testCompile 'com.squareup.assertj:assertj-android:1.0.0'
```

**Comment by gorkma** [comment]
+1 for this feature.

**Comment by dnkoutso** [comment]
+1 for this feature

**Comment by vekexasia** [comment]
I don't know if this is related or not. But if my project has a library project as dependency than its resources aren't imported :(

Example
Project "myproject" depends on "library" via "compile project(":library")", then the resources from ":library" arent usable from within any test case :(

**Comment by SuperJugy** [comment]
If your project is an app then it should get the resources. Unless the new Android version changed anything.

**Comment by vekexasia** [comment]
Indeed "myproject" is a library. I setted up a "com.android.application" project just for the tests.

**Comment by SuperJugy** [comment]
Since Android plugin is now supporting natively unit tests, I won't be maintaining this project anymore. Thanks for your support all this time.
