### ISSUE TITLE
How to depend on other project test classes?

### ISSUE THREAD

**Issue by dnkoutso** [JCAndKSolutions/android-unit-test#95]
We have a common project that provides a bunch of test-related utility classes. How can those be specified as a dependency to be included when executing tests?

Thanks!

**Comment by SuperJugy** [comment]
I guess you can make the test depnd on the project or jar via `testCompile` or something like that.

**Comment by dnkoutso** [comment]
Closing. I think I will move those files out into another project which I can depend on normally.

Thanks.
