### ISSUE TITLE
java.lang.NoClassDefFoundError: When running tests on Jenkins

### ISSUE THREAD

**Issue by w2ji** [JCAndKSolutions/android-unit-test#96]
Versions:
gradle - 2.2.1
android-unit-test - 2.1.1
gradle build tool - 1.0.0

We are getting 
java.lang.NoClassDefFoundError: android/support/v4/widget/DrawerLayoutImpl
19:03:47.419 [DEBUG] [TestEventLogger]         at java.lang.ClassLoader.defineClass1(Native Method)
when running tests on Jenkins. 

The tests run successfully on local machines, but when run on build server it cannot find the above class.

**Comment by SuperJugy** [comment]
Do you have the support repository in jenkins machine? a more complete stack trace could help.

**Comment by w2ji** [comment]
I fixed the issue by manually including the dependency in the testCompile scope. 

Thanks for the fast response!

**Comment by mttmllns** [comment]
@w2ji can you elaborate on your fix?

**Comment by calren** [comment]
@w2ji also wondering if you could elaborate on your fix because i'm facing the exact same problem. thanks!

**Comment by calren** [comment]
In case anybody is wondering, this weird bug can be resolved by running the following commands:
./gradlew clean assemble
./gradlew test

./gradlew clean assemble test will not work for some reason
