### ISSUE TITLE
error: `build/intermediates/res/debug/values` is not a directory.

### ISSUE THREAD

**Issue by tomerlevi444** [JCAndKSolutions/android-unit-test#99]
The cause of the issue:
Resources are copied to `build/intermediates/res/test/debug` instead of `build/intermediates/res/debug`. But, when I run `testDebug` task, it searches for directory `build/intermediates/res/debug/values`.

The error can be reproducted here: `https://github.com/klarna/klarna-on-demand-android/tree/708bf69091162e85215be41bdf87815a778e3b8a`.

**Comment by SuperJugy** [comment]
the `build/intermediates/res/debug` folder is created by the android plugin. The android plugin would not copy resources into a folder named `build/intermediate/res/test/debug` and this plugin is not copying any resources. I see in your gradle though that you are setting `androidTest.setRoot('src/test')` and that is wrong. androidTest is for instrumentation tests, not unit tests with robolectric. if you remove that line then you should have no problem.

**Comment by tomerlevi444** [comment]
I have removed the line `androidTest.setRoot('src/test')`, and it still acts the same. The folder  `build/intermediates/res/debug` is not created, and instead, there's `build/intermediate/res/test/debug`.
That's very weird.

**Comment by SuperJugy** [comment]
Can you post the file hierarchy inside the build folder? and can you run the test task instead of testDebug to see what it does?

**Comment by tomerlevi444** [comment]
after running test task, this is the build directory hierarchy:

build
|-- dependency-cache
|-- generated
|   |-- res
|   |   `-- rs
|   |       |-- debug
|   |       `-- test
|   |           `-- debug
|   `-- source
|       |-- aidl
|       |   `-- debug
|       |-- buildConfig
|       |   `-- debug
|       |       `-- com
|       |           `-- klarna
|       |               `-- ondemand
|       |-- r
|       |   `-- debug
|       |       `-- com
|       |           `-- klarna
|       |               `-- ondemand
|       `-- rs
|           |-- debug
|           `-- test
|               `-- debug
|-- intermediates
|   |-- bundles
|   |   `-- debug
|   |       |-- aidl
|   |       |-- assets
|   |       `-- res
|   |           |-- layout
|   |           |-- menu
|   |           |-- values
|   |           |-- values-sv
|   |           |-- values-v21
|   |           `-- values-w820dp-v13
|   |-- classes
|   |   `-- debug
|   |       `-- com
|   |           |-- jockeyjs
|   |           |   `-- util
|   |           `-- klarna
|   |               `-- ondemand
|   |-- dependency-cache
|   |   `-- debug
|   |-- incremental
|   |   |-- aidl
|   |   |   `-- debug
|   |   |-- mergeAssets
|   |   |   `-- debug
|   |   |-- mergeResources
|   |   |   `-- test
|   |   |       `-- debug
|   |   `-- packageResources
|   |       `-- debug
|   |-- lint
|   |-- manifests
|   |   |-- test
|   |   |   `-- debug
|   |   `-- tmp
|   |-- ndk
|   |   `-- debug
|   |       |-- lib
|   |       `-- obj
|   |-- res
|   |   `-- test
|   |       `-- debug
|   |           |-- layout
|   |           |-- menu
|   |           |-- values
|   |           |-- values-sv
|   |           |-- values-v21
|   |           `-- values-w820dp-v13
|   `-- rs
|       |-- debug
|       |   |-- lib
|       |   `-- obj
|       `-- test
|           `-- debug
|               |-- lib
|               `-- obj
|-- outputs
|   `-- aar
|-- test-classes
|   `-- debug
|       |-- com
|       |   `-- klarna
|       |       `-- ondemand
|       `-- org
|           `-- mockito
|               `-- configuration
|-- test-report
|   `-- debug
|       |-- classes
|       |-- css
|       |-- js
|       `-- packages
|-- test-results
|   `-- binary
|       `-- testDebug
`-- tmp
    |-- compileDebugJava
    |-- compileTestDebugJava
    `-- packageDebugJar

**Comment by SuperJugy** [comment]
It is very weird that android plugin is not generating that folder. I would need some more time to dig into this.

**Comment by tomerlevi444** [comment]
It will be very much appreciated.

**Comment by SuperJugy** [comment]
Hey, have you figured out something else? because i don't know what else could be happening. if you could debug it, it would be great. Also, I'm seeing that the android plugin is about to provide native support for unit testing in JVM so this plugin might have its days counted.

**Comment by SuperJugy** [comment]
I don't know if this is related but could you do an experiment for me? Can you make a test program project that depends on your library? My theory is that since your library is not being depended on by another project, then the plugin is not generating the intermediate resources. Supposedly, this plugin added a task dependency on the instrumentation tests so that this resources were generated, but as you apparently discovered, this test resources are not in `intermediates/res/flavor/debug` they are in `intermediates/res/test/debug`. I think I will have to add a special case for the library projects to search for resources in the right place. I guess that must people had a program project depending on the library and that forced the creation of the folders and we never discovered until now.

**Comment by SuperJugy** [comment]
Hey, I just did a test with a library without an app and it work perfectly. So my guess is that you are changing something in your gradle build file that is affecting the plugin. if you could remove things from your build file and try to keep it as simple as possible you might get the error gone and then you can start returning all the extra bits to find the culprit.

**Comment by tomerlevi444** [comment]
In the library's repositry ([here] (https://github.com/klarna/klarna-on-demand-android)), there's an example application that demonstrates the usage of it. 
The example application depends on this library, but the build still behaves the same.

**Comment by tomerlevi444** [comment]
Can you share the test you did?

**Comment by SuperJugy** [comment]
The test i did was to copy the example project in this repo and remove the app project. Then i ran a clean build with just the library.

**Comment by tomerlevi444** [comment]
That's probably because the [build.gradle](https://github.com/klarna/klarna-on-demand-android/blob/master/klarna-on-demand/build.gradle#L43) file currently contains a workaround that copies the `res/test/debug` folder to `res/debug`:
`task copyTestResources(type: Copy) {
    from "build/intermediates/res/test"
    into "build/intermediates/res"
}

afterEvaluate {
    tasks.findByPath('testDebugClasses').dependsOn copyTestResources
}`

**Comment by SuperJugy** [comment]
I saw your workaround, but I was talking about the examplo project in *THIS* repo. This repo doesn't have that workaround. When I run the simple library project in this repo without the app project, it still creates the `res/debug` and also the `res/test/debug`folders without any copy. So my point is, something is going on with your project that it is not generating those folders.

**Comment by SuperJugy** [comment]
Since we never figured out what was happening and android plugin is now natively supporting unit tests, I will deprecate this plugin and won't be fixing any new issue. Sorry if this is trouble for you. Good luck and hope the new android plugin covers your needs.
